#!/usr/bin/env ruby
require_relative './lib/parking_lot'
require 'rspec';
require 'pry';
require 'simplecov'

def process_input(input)
 parking_lot = nil
  input.split("\n").each do |input|
    input_split = input.split(/\s/)
    cmd = input_split[0]
    if cmd == 'create_parking'
      no_of_spots = input_split[1]
      parking_lot = ParkingLot.new(no_of_spots)
    else
      parking_lot.send(cmd, *([input_split[1], input_split[2]].compact))
    end
  end
end

def main
  SimpleCov.start
  RSpec::Core::Runner.run([File.dirname(__FILE__) + '/specs'])
  if (ARGV.length == 0)
    puts "Please enter file parameter"
    return
  else
    begin
      input = File.read(ARGV[0])
    rescue StandardError => e
      puts "Error reading file #{ e }"
      return
    end
  end
  begin
    process_input(input)
  rescue StandardError => e
  puts "Error processing input. Error - #{ e }"
  end
end

main()
